spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-catalog
          uri: lb://PRODUCT-CATALOG
          predicates:
            - Path=/product/**

eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000
